apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mystatefulset
spec:
  selector:
    matchLabels:
      app: percona
  serviceName: percona
  replicas: 3
  template:
    metadata:
      labels:
        app: percona
    spec:
      initContainers:
        - name: check
          image: busybox
          volumeMounts:
          -  mountPath: /etc/my.cnf.d/
             name: sql-conf
          command:
            [
              "sh",
              "-c",
              'echo "[mysqld]" > /etc/my.cnf.d/server_id.cnf  && S=$(expr $(echo $HOSTNAME | cut -d- -f2) + 1 ) && echo server-id = $S >> /etc/my.cnf.d/server_id.cnf && echo "log_bin = /var/lib/mysql/mysql-bin.log" >> /etc/my.cnf.d/server_id.cnf'
            ]
      containers:
      - name: percona
        image: percona:latest
        ports:
        - containerPort: 3306
          name: percona
        volumeMounts:
        -  mountPath: /etc/my.cnf.d/
           name: sql-conf
        envFrom:
          - configMapRef:
              name: s1
        lifecycle:
          postStart:
            exec:
              command: ["bin/sh", "-c" , "curl https://raw.githubusercontent.com/MohammadChr/Percona-statefullset/main/postcontainer.sh | bash"]
      volumes:
      -  name: sql-conf
         emptyDir: {}
